FROM oven/bun:1.1.42

# コンテナ内のwork dirを設定
WORKDIR /src

# 環境変数を設定し、ポートとホストを指定
ARG API_URL
ARG SITE_URL
ARG PROXY_URL
ARG GTAG
ARG SLACK_HOOK_URL
ARG BASIC_USER
ARG BASIC_PASS
ARG API_KEY
ARG TURNSTILE_SITE_KEY
ARG TURNSTILE_SECRET_KEY

ENV PORT 8080
ENV HOST 0.0.0.0
ENV API_URL ${API_URL}
ENV SITE_URL ${SITE_URL}
ENV PROXY_URL ${PROXY_URL}
ENV GTAG ${GTAG}
ENV SLACK_HOOK_URL ${SLACK_HOOK_URL}
ENV BASIC_USER ${BASIC_USER}
ENV BASIC_PASS ${BASIC_PASS}
ENV API_KEY ${API_KEY}
ENV TURNSTILE_SITE_KEY ${TURNSTILE_SITE_KEY}
ENV TURNSTILE_SECRET_KEY ${TURNSTILE_SECRET_KEY}

# package.jsonをコピーして、パッケージのインストール
COPY package.json ./
COPY bun.lockb ./
RUN bun install

# ソースをコピーして、ビルド
COPY . .
RUN bun nbuild

# コンテナが起動したら、nuxtを起動するよう指定
CMD [ "bun", "start"]